config/routes.rb
Rails.application.routes.draw do
  root 'doctors#index'

  resources :patients
  resources :doctors do
    resources :appointment, only: [:index, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :patient
  belongs_to :doctor
end

app/models/doctor.rb
class Doctor < ApplicationRecord
    has_many :appointment
    has_many :patients, through: :appointment
    has_many :appointment, dependent: :destroy
  end

app/models/patient.rb
class Patient < ApplicationRecord
    has_many :appointment
    has_many :doctors, through: :appointment
    has_many :appointment, dependent: :destroy


    def full_name
      "#{self.first_name} #{self.last_name}"
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointment_controller.rb
class AppointmentController < ApplicationController
  before_action :set_doctor

  def index
    @doctors = @doctor.appointments.where(role: 'doctor')
    @job = @doctor.appointments.where(role: 'job')
    @patient = @doctor.appointments.where(role: 'patient')
  end

  def new
    @patients = Patient.all - @doctor.patients
    @appointment = @doctor.appointment.new
  end

  def create
    @appointment = @doctor.appointments.new(appointment_params)
    if @appointment.save
      redirect_to doctor_appointments_path(@doctor)
    else
      render :new
    end
  end

  def destroy
    @appointment = @doctor.appointments.find(params[:id])
    @appointment.destroy
    redirect_to doctor_appointments_path(@doctor)
  end

 private
   def set_doctor
     @doctor = doctor.find(params[:doctor_id]) 
   end

   def appointment_params
     params.require(:appointment).permit(:role, :user_id)
   end
end

app/controllers/doctors_controller.rb
class DoctorsController < ApplicationController
  before_action :set_doctor, only: [:show, :destroy]

  def index
    @doctors = Doctor.all
  end

  def show
    [:id])
  end

  def new
    @doctor = Doctor.new
  end

  def create
    @doctor = Doctor.new(doctor_params)

    if @doctor.save
      redirect_to @doctor
    else
      render :new
    end
  end

  def destroy
    @doctor.destroy
    redirect_to courses_path
  end

  private
    def set_doctor
      @doctor = Doctor.find(params[:id])
    end

    def doctor_params
      params.require(:doctor).permit(:name)
    end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :destroy]

  def index
    @patients = Patient.all
  end

  def show
  end

  def new
    @patient = Patient.new
  end

  def create
    @patient = Patient.new(patient_params)

    if @patient.save
      redirect_to @patient
    else
      render :new
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_path
  end

  private
    def set_patient
      @patient = Patient.find(params[:id])
    end

    def patient_params
      params.require(:patient).permit(:first_name, :last_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/helpers/doctors_helper.rb
module DoctorsHelper
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/appointment/index.html.erb
<h1><%= @doctor.name %>: Appointments</h1>
<%= link_to 'Add Appointment', new_doctor_appointment_path(@doctor) %>
<hr />

<h2>Doctor</h2>
<ul>
  <% @doctors.each do |doctor| %>
    <li>
      <%= doctor.user.full_name %>
      <br />
      <%= link_to 'Remove', doctor_appointment_path(@doctor, doctor), method: :delete %>
    </li>
  <% end %>
</ul>
<h2>Job</h2>
<ul>
  <% @jobs.each do |job| %>
    <li>
      <%= ta.user.full_name %>
      <br />
      <%= link_to 'Remove', doctor_appointment_path(@doctor, job), method: :delete %>
    </li>
 <% end %>
</ul>
<h2>Patient</h2>
<ul>
  <% @patients.each do |patient| %>
    <li>
      <%= patient.patient.full_name %>
      <br />
      <%= link_to 'Remove', doctor_appointment_path(@doctor, patient), method: :delete %>
   </li>
 <% end %>
</ul>

app/views/appointment/new.html.erb
<h1>Add Assignment</h1>
<%= form_with(model: [@doctor, @assignment], local: true, class: "ui form" ) do |f| %>
  <%= f.label :patient %>
  <%= f.select :patient_id, @patient.collect { |u| [u.full_name, u.id] } %>
  <br />
  <%= f.label :role %>
  <%= f.select :role, ['job', 'doctor', 'patient'] %>
  <br />
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/appointment/show.html.erb
<h1><%= @appointment.name %></h1>
<hr />
<br />
<%= link_to 'Appointments', doctor_appointment_path(@doctor), class: "ui primary button inverted" %>
<br />
<br />
<br />
<%= link_to "Delete Doctor", @doctor, method: :delete, class: "ui red button inverted" %>

app/views/doctors/index.html.erb
<h1>Doctors</h1>
<%= link_to 'Add Doctor', new_doctor_path %>
<hr />
<h2><%= @doctors.length <= 0 ? "No Doctors" : "" %></h2> 
<ul>
  <% @doctors.each do |doctor| %>
    <li>
      <%= link_to doctor.name, doctor %>
    </li>
  <% end %>
</ul>

app/views/doctors/new.html.erb
<h1>Add Doctor</h1>
<%= form_with(model: @doctor, local: true, class: "ui form" ) do |f| %>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name, required: true, placeholder: "Doctor Name" %>
  </div>
  <%= f.submit nil, class: "ui blue button inverted" %>
<% end %>

app/views/doctors/show.html.erb
<h1>Doctors#show</h1>
<p>Find me in app/views/doctors/show.html.erb</p>

app/views/layouts/_navbar.html.erb
<nav>
  <ul>
    <li>
      <%= link_to 'Doctor', doctor_path %>
    </li>
    <li>
      <%= link_to 'Add Doctor', new_doctor_path %>
    </li>
    <li>
      <%= link_to 'Patients', patients_path %>
    </li>
    <li>
      <%= link_to 'Add Patient', new_patient_path %>
    </li>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DoctorsApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <div class="ui container">
    <%= yield %>
  </div>
</body>
</html>

app/views/patients/index.html.erb
<h1>Patients</h1>
<%= link_to 'Add Patient', new_patient_path %>
<hr />
<ul>
  <% @Patients.each do |patient| %>
    <li>
      <%= link_to patient.full_name, patient %>
    </li>
<% end %>
</ul>

app/views/patients/new.html.erb
<h1>Add Patient</h1>
<%= form_with(model: @patient, local: true, class: "ui form") do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, required: true, autofocus: true, placeholder: "First Name" %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true, placeholder: "Last Name" %>
  </div>
  <%= f.submit nil, class: "ui green button inverted" %>
<% end %>

app/views/patients/show.html.erb
<h1><%= @patient.full_name %></h1>
<hr />
<h2>Doctors</h2>
<ul>
  <% @patient.doctors.each do |doctor| %>
    <li>
      <%= link_to doctor.name, doctor %>
    </li>
  <% end %>
</ul>
<br />
<br />
<br />
<%= link_to 'Delete patient', @patient, method: :delete, class: "ui red button inverted" %>